name = "MonteCarloFun"
uuid = "66adcf50-c72e-11e8-3fe6-5bdab3f3f839"
authors = ["Lamo28 <43213026+Lamo28@users.noreply.github.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
